version: "3.7"
services:
    blog:
        container_name: pea3nut-blog
        build:
            context: ./blog
            dockerfile: Dockerfile
            args:
                db_name: "pea"
                root_url: "http://127.0.0.1:8081"
        ports:
            - "8081:80"
        volumes:
            - ./blog/mysql-data:/var/lib/mysql
            - ./blog/wordpress:/app
        restart: on-failure
    info:
        container_name: pea3nut-info
        image: pea3nut/pea3nut-info:latest
        ports:
            - "8082:80"
        restart: on-failure
    short-night:
        container_name: short-night-homepage
        image: pea3nut/short-night-homepage:latest
        ports:
            - "8083:80"
        restart: on-failure
    aoning:
        container_name: aoning-wang
        build:
            context: ./aoning-wang
            dockerfile: Dockerfile
        ports:
            - "8085:80"
        restart: on-failure
    pxer:
        container_name: pxer
        image: pea3nut/pxer:master
        ports:
            - "8086:80"
        restart: on-failure
    pxer-homepage:
        container_name: pxer-homepage
        image: pea3nut/pxer-homepage:latest
        ports:
            - "8087:80"
        restart: on-failure
    pxer-homepage-2:
        container_name: pxer-homepage-2
        image: pea3nut/pxer-homepage-2:latest
        ports:
            - "8088:80"
        restart: on-failure
    point-hub:
        container_name: point-hub
        image: pea3nut/point-hub:master
        ports:
            - "8089:3000"
            - "8090:80"
        volumes:
            - ./points-data:/var/lib/mysql
        restart: on-failure
