#!/bin/bash

apt update
apt install -y node
apt install -y npm

password="$(cat /dev/urandom | sed 's/[^a-zA-Z0-9]//g'  |strings -n 5|head -n 1)"
username=pea3nut
filename=pea3nut-hub-patch.tar.gz


npm i -g local-web-server

tar -czvf pea3nut-hub-patch.tar.gz blog/mysql-data blog/wordpress/ pxer/ points-data/



echo "Please download the file by:"
echo "wget --http-user $username --http-password $password -O $filename"

ws --auth.user $username --auth.pass $password --spa $filename
