#!/bin/bash

set -e

if ! command -v node &> /dev/null
then
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
    export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install --lts
    nvm use --lts
fi


password=`tr -dc A-Za-z0-9 </dev/urandom | head -c 12`
username=pea3nut
filename=pea3nut-hub-patch.tar.gz
port=8991

npm i -g local-web-server

set +e
tar -czvf pea3nut-hub-patch.tar.gz \
    blog/mysql-data \
    blog/wordpress/ \
    points-data/ \
    /etc/letsencrypt \
;
exit_code=$?

if [ "$exit_code" != "1" ] && [ "$exit_code" != "0" ]; then
    exit $exit_code
fi
set -e

echo ''
echo '=================================='
echo "Packaged! Please download the file by:"
echo "wget --http-user $username --http-password $password -O $filename" 'http://[your public ip]:'$port
echo "./script/unpack $filename # after ./script/install"
echo ''

ws --auth.user $username --auth.pass $password --spa $filename --port $port
