#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


set -e

docker-compose pull $1
docker-compose build $1
docker-compose stop $1
docker-compose rm -f $1
docker-compose up -d $1

if [ "$1" = "gpt" ]; then
    $DIR/set-gpt-key
fi
